version: '3.1'

services:
  seavisiondatafetcher:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=mydbuser
      - SPRING_DATASOURCE_PASSWORD=mydbpass
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: mydbuser
      POSTGRES_PASSWORD: mydbpass
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
