version: '3.1'

services:
  seavisiondatafetcher_test:
    container_name: seavisiondatafetcher_test
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_test:5432/metrics-data
      - SPRING_DATASOURCE_USERNAME=metrics-data
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - AWS_ACCESS_KEY_ID=accesskey
      - AWS_SECRET_ACCESS_KEY=secretkey
    depends_on:
      - db_test
      - sqs_test

  db_test:
    image: postgres:alpine
    container_name: db_dest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=metrics-data
      - POSTGRES_PASSWORD=compose-postgres

  sqs_test:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sqs
