version: '3.1'

services:
  seavisiondatafetcher_test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbtest:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    env_file:
      - src/test/resources/application.properties
    depends_on:
      - dbtest

  dbtest:
    image: postgres:13.1-alpine
    container_name: dbdest
    ports:
      - "5432:5432"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    env_file:
      - src/test/resources/application.properties
    volumes:
      - dbtest_data:/var/lib/postgresql/data

volumes:
  dbtest_data:
