version: '3.1'

services:
  seavisiondatafetcher_test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=test
    env_file:
      - src/test/resources/application.properties
    depends_on:
      - db_test

  db_test:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: mydbuser
      POSTGRES_PASSWORD: mydbpass
    env_file:
      - src/test/resources/application.properties
    volumes:
      - db_test_data:/var/lib/postgresql/data

volumes:
  db_test_data:
