name: Check Valid Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # Define services needed for testing
    services:
      db_test:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: metrics-data
          POSTGRES_PASSWORD: compose-postgres
      sqs_test:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
          - 4571:4571
        env:
          SERVICES: sqs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Build with maven and run tests
        run: mvn clean --batch-mode --update-snapshots package
