name: Deploy to lambda

on:
  pull_request:
    branches:
      - main
#     types:
#       - closed

jobs:
  if_merged:
#     if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'
          cache: maven
      - name: Package to jar
        run: mvn package
      - name: update lambda 
        uses: asafmaoz1234/aws-lambda-update-jar-action@1.1
        with:
          lambda-name: 'weather-java'
          snapshot-name: 'lambda-beach-time-1.0-SNAPSHOT.jar'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
